# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d41894ec3afbbca90175333d7a9d150c6b68159105c8d3bc323ee82c8c4938b3cff7219b659432bb7e82a876470e3af4a56ba46090cde90747206fb77e79ef9

test:
  secret_key_base: 019a4b1944e7f7fa477fa2bccef951b08a62c03db0204556e21be4dbf32b5e935c7ded94c9e8c3c80a904aa4fe57b1ef6edd236ff7459033c2aed4f4bff10b1c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 9bcb698e2604cd5ff0404d2be5956fd98ee1d58457907d4a3d02d208d19f8fbb9c9810019b6259f6a770f2f7e494a98e0fdb1cfe2138e27f1256d212c58e1185
